{
  "altLangUrl": {
    "en": "https://design.canada.ca",
    "fr": "https://canada-ca.github.io/systeme-conception"
  },
  "analytics": {
    "provider": {
      "google": {
        "tracking_id": "GTM-KMVB8C2"
      },
      "adobe": {
        "tracking_id": "be5dfd287373/0127575cd23a/launch-f7c3e6060667",
        "service": "ESDC-EDSC",
        "gcaaterms": "ESDC-EDSC_CanadacaDesign-ConceptionCanadaca"
      }
    }
  },
  "author": {
    "en": "Employment and Social Development Canada"
  },
  "baseurl": "",
  "exclude": [
    ".editorconfig",
    ".jekyll-cache",
    ".gitignore",
    ".github",
    "*.gpg",
    "*.py",
    "*.tmp",
    "CNAME",
    "CODE_OF_CONDUCT.md",
    "CONTRIBUTING.md",
    "design-system.code-workspace",
    "gcweb-jekyll.gemspec",
    "Gemfile",
    "Gemfile.lock",
    "GEMINI.md",
    "LICENSE*",
    "log_*",
    "netlify.toml",
    "node_modules",
    "package*.json",
    "README.md",
    "screenshot.*",
    "SECURITY.md",
    "vendor",
    "venv"
  ],
  "include": [
    "_redirects"
  ],
  "institutionopt": "esdc",
  "global": {
    "contextualFooter": {
      "title": {
        "en": "Canada.ca Experience Office (CEO)"
      },
      "links": {
        "en": [{
          "url": "https://blog.canada.ca/contact-us",
          "text": "Contact us"
        }]
      }
    },
    "feedbackPath": {
      "en": "https://www.canada.ca/etc/designs/canada/wet-boew/assets/feedback/page-feedback-en.html"
    },
    "lang": "en",
    "sitemenuPath": {
      "en": "https://www.canada.ca/content/dam/canada/sitemenu/sitemenu-v2-en.html"
    }
  },
  "language": {
    "en": "English",
    "fr": "Fran√ßais"
  },
  "plugins": [
    "jekyll-remote-theme"
  ],
  "remote_theme": "wet-boew/gcweb-jekyll",
  "themeopt": "Policies",
  "title": "Canada.ca design",
  "url": "https://design.canada.ca",
  "urlconception": "https://canada-ca.github.io/systeme-conception",
  "urlcanadaca": "https://www.canada.ca",
  "urlblogca": "https://blog.canada.ca",
  "emails": {
    "dto": "cds.dto-btn.snc@servicecanada.gc.ca",
    "atip": "ATIP.AIPRP@tbs-sct.gc.ca"
  },
  "webmaster_verifications": {
    "google": "Nt_CftRIypA9xVS7Znb2VkrsYbtIDuFWHryxSAC6OwM",
    "yandex": "b8834a99b9021b0e"
  },
  "defaults": [{
      "scope": {
        "path": "**/*.md"
      },
      "values": {
        "css": [
          "https://use.fontawesome.com/releases/v5.15.4/css/all.css",
          "/css/custom.css"
        ],
        "feedback": true,
        "feedbackData": {
          "theme": "AboutGov"
        },
        "lang": "en",
        "layout": "default",
        "pageclass": "cnt-wdth-lmtd",
        "script": [
          "/js/url-swap.js"
        ],
        "share": true
      }
    },
    {
      "scope": {
        "path": "/*.md"
      },
      "values": {
        "breadcrumbs": [{
            "link": "https://www.canada.ca/en/government/about-canada-ca.html",
            "title": "About Canada.ca"
          },
          {
            "link": "/",
            "title": "Design"
          }
        ]
      }
    },
    {
      "scope": {
        "path": "coded-layout/*.md"
      },
      "values": {
        "breadcrumbs": [{
            "link": "https://www.canada.ca/en/government/about-canada-ca.html",
            "title": "About Canada.ca"
          },
          {
            "link": "/",
            "title": "Design"
          },
          {
            "link": "https://www.canada.ca/en/government/about/design-system/pattern-library.html",
            "title": "Templates and patterns"
          },
          {
            "link": "/recommended-templates/generic-destination.html",
            "title": "Generic destination template"
          }
        ]
      }
    },
    {
      "scope": {
        "path": "survey"
      },
      "values": {
        "breadcrumbs": [{
            "title": "About Canada.ca",
            "link": "https://www.canada.ca/en/government/about-canada-ca.html"
          },
          {
            "title": "Analytics and feedback",
            "link": "https://www.canada.ca/en/analytics.html"
          },
          {
            "title": "GC Task Success Survey",
            "link": "/survey/index.html"
          }
        ]
      }
    },
    {
      "scope": {
        "path": "architecture"
      },
      "values": {
        "breadcrumbs": [{
            "title": "About Canada.ca",
            "link": "https://www.canada.ca/en/government/about-canada-ca.html"
          },
          {
            "title": "Design",
            "link": "/"
          },
          {
            "title": "Information architecture specification",
            "link": "/architecture/canada-content-information-architecture-specification.html"
          }
        ]
      }
    },
    {
      "scope": {
        "path": "common-design-patterns/*.md"
      },
      "values": {
        "breadcrumbs": [{
            "title": "About Canada.ca",
            "link": "https://www.canada.ca/en/government/about-canada-ca.html"
          },
          {
            "title": "Design",
            "link": "/"
          },
          {
            "title": "Templates and patterns",
            "link": "/pattern-library.html"
          }
        ]
      }
    },
    {
      "scope": {
        "path": "common-design-patterns/global-header/*.md"
      },
      "values": {
        "breadcrumbs": [{
            "title": "About Canada.ca",
            "link": "https://www.canada.ca/en/government/about-canada-ca.html"
          },
          {
            "title": "Design",
            "link": "/"
          },
          {
            "title": "Templates and patterns",
            "link": "/pattern-library.html"
          },
          {
            "title": "Global header",
            "link": "/common-design-patterns/global-header.html"
          }
        ],
        "permalink": "/common-design-patterns/:basename:output_ext"
      }
    },
    {
      "scope": {
        "path": "common-design-patterns/global-footer/*.md"
      },
      "values": {
        "breadcrumbs": [{
            "title": "About Canada.ca",
            "link": "https://www.canada.ca/en/government/about-canada-ca.html"
          },
          {
            "title": "Design",
            "link": "/"
          },
          {
            "title": "Templates and patterns",
            "link": "/pattern-library.html"
          },
          {
            "title": "Global footer",
            "link": "/common-design-patterns/site-footer.html"
          }
        ],
        "permalink": "/common-design-patterns/:basename:output_ext"
      }
    },
    {
      "scope": {
        "path": "community/*.md"
      },
      "values": {
        "breadcrumbs": [{
            "link": "https://www.canada.ca/en/government/about-canada-ca.html",
            "title": "About Canada.ca"
          },
          {
            "link": "/",
            "title": "Design"
          },
          {
            "link": "/community/landing.html",
            "title": "Community"
          }
        ]
      }
    },
    {
      "scope": {
        "path": "continuous-improvement/*.md"
      },
      "values": {
        "breadcrumbs": [{
            "link": "https://www.canada.ca/en/government/about-canada-ca.html",
            "title": "About Canada.ca"
          },
          {
            "link": "/",
            "title": "Design"
          },
          {
            "link": "/continuous-improvement.html",
            "title": "Continuous improvement"
          }
        ]
      }
    },
    {
      "scope": {
        "path": "continuous-improvement.md"
      },
      "values": {
        "breadcrumbs": [{
            "link": "https://www.canada.ca/en/government/about-canada-ca.html",
            "title": "About Canada.ca"
          },
          {
            "link": "/",
            "title": "Design"
          }
        ]
      }
    },
    {
      "scope": {
        "path": "crisis/*.md"
      },
      "values": {
        "breadcrumbs": [{
            "link": "https://www.canada.ca/en/government/about-canada-ca.html",
            "title": "About Canada.ca"
          },
          {
            "link": "/",
            "title": "Design"
          },
          {
            "link": "/crisis/content.html",
            "title": "Crisis communications content design checklist"
          }
        ]
      }
    },
    {
      "scope": {
        "path": "feedback/*.md"
      },
      "values": {
        "breadcrumbs": [{
            "title": "About Canada.ca",
            "link": "https://www.canada.ca/en/government/about-canada-ca.html"
          },
          {
            "title": "Analytics and feedback",
            "link": "https://www.canada.ca/en/analytics.html"
          },
          {
            "title": "Page feedback",
            "link": "/feedback/index.html"
          }
        ]
      }
    },
    {
      "scope": {
        "path": "guidance/*.md"
      },
      "values": {
        "breadcrumbs": [{
            "link": "https://www.canada.ca/en/government/about-canada-ca.html",
            "title": "About Canada.ca"
          },
          {
            "link": "/",
            "title": "Design"
          },
          {
            "link": "/guidance",
            "title": "Guidance"
          }
        ]
      }
    },
    {
      "scope": {
        "path": "guidance/ai/*.md"
      },
      "values": {
        "breadcrumbs": [{
            "link": "https://www.canada.ca/en/government/about-canada-ca.html",
            "title": "About Canada.ca"
          },
          {
            "link": "https://design.canada.ca",
            "title": "Design"
          },
          {
            "link": "https://design.canada.ca/guidance/index.html",
            "title": "Guidance"
          },
          {
            "link": "https://design.canada.ca/guidance/ai/index.html",
            "title": "AI help applications"
          }
        ]
      }
    },
    {
      "scope": {
        "path": "layout/*.md"
      },
      "values": {
        "breadcrumbs": [{
            "link": "https://www.canada.ca/en/government/about-canada-ca.html",
            "title": "About Canada.ca"
          },
          {
            "link": "/",
            "title": "Design"
          },
          {
            "link": "https://www.canada.ca/en/government/about/design-system/pattern-library.html",
            "title": "Templates and patterns"
          }
        ]
      }
    },
    {
      "scope": {
        "path": "mandatory-templates/*.md"
      },
      "values": {
        "breadcrumbs": [{
            "link": "https://www.canada.ca/en/government/about-canada-ca.html",
            "title": "About Canada.ca"
          },
          {
            "link": "/",
            "title": "Design"
          },
          {
            "link": "https://www.canada.ca/en/government/about/design-system/pattern-library.html",
            "title": "Templates and patterns"
          }
        ]
      }
    },
    {
      "scope": {
        "path": "recommended-templates/*.md"
      },
      "values": {
        "breadcrumbs": [{
            "link": "https://www.canada.ca/en/government/about-canada-ca.html",
            "title": "About Canada.ca"
          },
          {
            "link": "/",
            "title": "Design"
          },
          {
            "link": "https://www.canada.ca/en/government/about/design-system/pattern-library.html",
            "title": "Templates and patterns"
          }
        ]
      }
    },
    {
      "scope": {
        "path": "styles/*.md"
      },
      "values": {
        "breadcrumbs": [{
            "link": "https://www.canada.ca/en/government/about-canada-ca.html",
            "title": "About Canada.ca"
          },
          {
            "link": "/",
            "title": "Design"
          },
          {
            "link": "https://www.canada.ca/en/government/about/design-system/pattern-library.html",
            "title": "Templates and patterns"
          }
        ]
      }
    },
    {
      "scope": {
        "path": "style-guide/*.md"
      },
      "values": {
        "breadcrumbs": [{
            "title": "About Canada.ca",
            "link": "https://www.canada.ca/en/government/about-canada-ca.html"
          },
          {
            "title": "Design",
            "link": "/"
          },
          {
            "title": "Canada.ca Content Style Guide",
            "link": "/style-guide/"
          }
        ]
      }
    },
    {
      "scope": {
        "path": "style-guide/index.md"
      },
      "values": {
        "breadcrumbs": [{
            "title": "About Canada.ca",
            "link": "https://www.canada.ca/en/government/about-canada-ca.html"
          },
          {
            "title": "Design",
            "link": "/"
          }
        ]
      }
    },
    {
      "scope": {
        "path": "about"
      },
      "values": {
        "breadcrumbs": [{
            "title": "About Canada.ca",
            "link": "https://www.canada.ca/en/government/about-canada-ca.html"
          },
          {
            "link": "/",
            "title": "Design"
          }
        ]
      }
    },
    {
      "scope": {
        "path": "about/index.md"
      },
      "values": {
        "breadcrumbs": true
      }
    },
    {
      "scope": {
        "path": "about/digital-transformation-office.md"
      },
      "values": {
        "breadcrumbs": [{
          "title": "About Canada.ca",
          "link": "https://www.canada.ca/en/government/about-canada-ca.html"
        }]
      }
    },
    {
      "scope": {
        "path": "style-guide/*.md"
      },
      "values": {
        "breadcrumbs": [{
            "title": "About Canada.ca",
            "link": "https://www.canada.ca/en/government/about-canada-ca.html"
          },
          {
            "title": "Design",
            "link": "/"
          },
          {
            "title": "Canada.ca Content Style Guide",
            "link": "/style-guide/"
          }
        ]
      }
    },
    {
      "scope": {
        "path": "research-summaries/*.md"
      },
      "values": {
        "section-title": "Research summary",
        "breadcrumbs": [{
            "title": "About Canada.ca",
            "link": "https://www.canada.ca/en/government/about-canada-ca.html"
          },{
            "title": "Design",
            "link": "/"
          },{
            "title": "Research summaries",
            "link": "/research-summaries/"
          }
        ]
      }
    },
    {
      "scope": {
        "path": "research-summaries/index.md"
      },
      "values": {
        "section-title": "",
        "breadcrumbs": [{
          "title": "About Canada.ca",
          "link": "https://www.canada.ca/en/government/about-canada-ca.html"
        },{
            "title": "Design",
            "link": "/"
          }]
      }
    },
    {
      "scope": {
        "path": "partners/*.md"
      },
      "values": {
        "section-title": "Working with partners",
        "breadcrumbs": [{
            "title": "About Canada.ca",
            "link": "https://www.canada.ca/en/government/about-canada-ca.html"
          },
          {
            "title": "Working with partners",
            "link": "/partners/"
          }
        ]
      }
    },
    {
      "scope": {
        "path": "partners/index.md"
      },
      "values": {
        "section-title": "",
        "breadcrumbs": [{
          "title": "About Canada.ca",
          "link": "https://www.canada.ca/en/government/about-canada-ca.html"
        }]
      }
    },
    {
      "scope": {
        "path": "pattern-library.md"
      },
      "values": {
        "breadcrumbs": [{
            "title": "About Canada.ca",
            "link": "https://www.canada.ca/en/government/about-canada-ca.html"
          },
          {
            "title": "Design",
            "link": "/"
          }
        ]
      }
    },
    {
      "scope": {
        "path": "find-right-template-design-pattern-web-content.md"
      },
      "values": {
        "breadcrumbs": [{
            "title": "About Canada.ca",
            "link": "https://www.canada.ca/en/government/about-canada-ca.html"
          },
          {
            "title": "Design",
            "link": "/"
          },
          {
            "title": "Templates and patterns",
            "link": "/pattern-library.html"
          }
        ]
      }
    },
    {
      "scope": {
        "path": "index.md"
      },
      "values": {
        "breadcrumbs": [{
          "title": "About Canada.ca",
          "link": "https://www.canada.ca/en/government/about-canada-ca.html"
        }]
      }
    }
  ]
}
